# cpp/tests/gen_lower_table.py
"""
Regenerates the data behind pytext::lower (Python's str.lower()):

    cpp/src/lower_table.inc        range-compressed tables compiled into the library
    cpp/tests/golden_lower.h       flat, uncompressed golden lists the unit test checks every code point against

    python cpp/tests/gen_lower_table.py            # rewrite both files
    python cpp/tests/gen_lower_table.py --check    # exit 1 if either file differs from a fresh run

Everything is read from Python's own str.lower() over ALL code points (surrogates excluded: UTF-8 cannot carry
them), so the tables are exactly what the running Python does. The data belongs to one Unicode version; the
generator refuses to run on another one, so a re-run is byte-identical.

str.lower() is "simple mapping per character" plus two special cases that CPython implements itself:
  * U+0130 lowercases to two code points (i, U+0307);
  * U+03A3 (capital sigma) lowercases to U+03C2 (final sigma) when it ends a word, else U+03C3:
    the nearest non-"case ignorable" character before it is "cased" AND the nearest non-ignorable character
    after it is not cased (or the text ends).
Python does not expose the Cased / Case_Ignorable properties, so they are probed through the sigma rule itself:
    P1(c) = ("c" + sigma).lower() ends with final sigma    <=>  c is cased and not case-ignorable
    P2(c) = ("A" + c + sigma).lower() ends with final sigma <=>  c is case-ignorable, or cased
Together: ignorable = P2 and not P1; "effective cased" = P1.
"""
import argparse
import sys
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TABLE_OUT = ROOT / "cpp" / "src" / "lower_table.inc"
GOLDEN_OUT = ROOT / "cpp" / "tests" / "golden_lower.h"
UNICODE_VERSION = "15.0.0"  # Python 3.12
SIGMA = "Σ"
FINAL_SIGMA = "ς"


def code_points():
    return [c for c in range(0x110000) if not 0xD800 <= c <= 0xDFFF]


def collect():
    if unicodedata.unidata_version != UNICODE_VERSION:
        raise SystemExit(
            f"this table is generated for Unicode {UNICODE_VERSION}; this Python has {unicodedata.unidata_version}"
        )
    mapping = {}  # code point -> lowercase code point, for the single-character mappings
    p1, p2 = [], []
    for c in code_points():
        ch = chr(c)
        low = ch.lower()
        if c == 0x130:
            assert low == "i̇"
        else:
            assert len(low) == 1, hex(c)
            if ord(low) != c:
                mapping[c] = ord(low)
        if (ch + SIGMA).lower().endswith(FINAL_SIGMA):
            p1.append(c)
        if ("A" + ch + SIGMA).lower().endswith(FINAL_SIGMA):
            p2.append(c)
    return mapping, p1, p2


def lower_ranges(mapping):
    """(lo, hi, step, delta) runs: every `step`-th code point from lo to hi maps by +delta (step 1 or 2)."""
    keys = sorted(mapping)
    ranges = []
    i = 0
    while i < len(keys):
        lo = keys[i]
        delta = mapping[lo] - lo
        step = 1
        j = i
        if i + 1 < len(keys) and mapping[keys[i + 1]] - keys[i + 1] == delta and keys[i + 1] - lo in (1, 2):
            step = keys[i + 1] - lo
            j = i + 1
            while j + 1 < len(keys) and keys[j + 1] - keys[j] == step and mapping[keys[j + 1]] - keys[j + 1] == delta:
                j += 1
        ranges.append((lo, keys[j], step, delta))
        i = j + 1
    return ranges


def class_ranges(p1, p2):
    """(lo, hi, kind) runs of consecutive code points with the same non-zero kind: 1 = case-ignorable, 2 = cased."""
    first, both = set(p1), set(p2)
    kinds = {}
    for c in both | first:
        if c in first:
            kinds[c] = 2
        else:
            kinds[c] = 1  # in P2 only: case-ignorable
    ranges = []
    for c in sorted(kinds):
        if ranges and ranges[-1][1] + 1 == c and ranges[-1][2] == kinds[c]:
            ranges[-1] = (ranges[-1][0], c, kinds[c])
        else:
            ranges.append((c, c, kinds[c]))
    return ranges


def wrap(items, per_line):
    lines = []
    for i in range(0, len(items), per_line):
        lines.append("    " + " ".join(items[i : i + per_line]))
    return "\n".join(lines)


def table_text(mapping, p1, p2):
    lows = lower_ranges(mapping)
    classes = class_ranges(p1, p2)
    out = [
        "// cpp/src/lower_table.inc -- GENERATED by cpp/tests/gen_lower_table.py. Do not edit by hand.",
        f"// Python 3.12 / Unicode {UNICODE_VERSION}: str.lower() as range tables (see the generator for how the",
        "// Cased / Case_Ignorable properties behind the final-sigma rule were obtained).",
        "",
        "// Single-character lowercase mappings: every `step`-th code point in [lo, hi] maps to code point + delta.",
        "// Sorted by lo. U+0130 and the final-sigma rule are handled in code.",
        "const LowerRange kLowerRanges[] = {",
        wrap([f"{{0x{lo:04X}, 0x{hi:04X}, {step}, {delta}}}," for lo, hi, step, delta in lows], 3),
        "};",
        "",
        "// Case classes for the final-sigma rule: 1 = case-ignorable, 2 = cased (and not case-ignorable). Sorted by lo.",
        "const CaseClassRange kCaseClasses[] = {",
        wrap([f"{{0x{lo:04X}, 0x{hi:04X}, {kind}}}," for lo, hi, kind in classes], 4),
        "};",
        "",
    ]
    return "\n".join(out)


def hex_list(values, per_line=12):
    return wrap([f"0x{v:X}," for v in values], per_line)


def golden_text(mapping, p1, p2):
    pairs = sorted(mapping.items())
    out = [
        "// cpp/tests/golden_lower.h -- GENERATED by cpp/tests/gen_lower_table.py. Do not edit by hand.",
        "// Flat, uncompressed results of Python's str.lower(), used to check pytext::lower on every code point.",
        "#pragma once",
        "#include <cstdint>",
        "",
        "// {code point, lowercase code point} for every code point whose lowercase is a different single character.",
        "// (U+0130 lowercases to two characters and is checked separately.)",
        "static const std::uint32_t kGoldenLower[][2] = {",
        wrap([f"{{0x{c:X}, 0x{m:X}}}," for c, m in pairs], 5),
        "};",
        "",
        "// Code points c for which (c + capital sigma).lower() ends in a FINAL sigma.",
        "static const std::uint32_t kGoldenFinalAfterC[] = {",
        hex_list(p1),
        "};",
        "",
        'static const std::uint32_t kGoldenFinalAfterAC[] = {  // ... for ("A" + c + capital sigma).lower()',
        hex_list(p2),
        "};",
        "",
    ]
    return "\n".join(out)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    mapping, p1, p2 = collect()
    files = {TABLE_OUT: table_text(mapping, p1, p2), GOLDEN_OUT: golden_text(mapping, p1, p2)}
    bad = False
    for path, text in files.items():
        data = text.encode("ascii")
        if args.check:
            if not path.exists() or path.read_bytes() != data:
                print(f"{path} is out of date")
                bad = True
        else:
            path.write_bytes(data)
            print(f"wrote {path} ({len(data)} bytes)")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
