# cpp/tests/gen_shell_golden.py
"""
Regenerates cpp/tests/golden_shell.h: exact strings the Python shell (meradb/repl.py) produces for the
pieces the C++ shell reimplements -- banner, .help output, prompts and result rendering -- once with colour
off and once with colour on (a pretend terminal), so the C++ unit tests can compare byte for byte.

    python cpp/tests/gen_shell_golden.py
"""
import argparse
import contextlib
import io
import json
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUT = Path(__file__).with_name("golden_shell.h")


class FakeTerminal(io.TextIOWrapper):
    """A stdout that claims to be a terminal, so repl.py switches colour on."""

    def __init__(self):
        super().__init__(io.BytesIO(), encoding="utf-8")

    def isatty(self):
        return True


class FakeBackend:
    def __init__(self, db, txn):
        self.current_db, self.in_transaction = db, txn


def capture(fn, *args):
    buffer = io.StringIO()
    with contextlib.redirect_stdout(buffer):
        fn(*args)
    return buffer.getvalue()


def child(mode):
    """Runs in a fresh interpreter: prints {name: text} as JSON."""
    if mode == "color":
        sys.stdout = FakeTerminal()
    sys.path.insert(0, str(ROOT))
    from meradb import repl
    from meradb.engine import Result

    repl.time.sleep = lambda seconds: None  # the reveal animation pauses only when colour is on
    assert repl._COLOR == (mode == "color"), "colour mode was not what the generator asked for"
    samples = {
        "banner": capture(repl.print_banner, "1.0.0", "local (/data/x)"),
        "banner_server": capture(repl.print_banner, "1.0.0", "127.0.0.1:6372"),
        "help_full": capture(repl.handle_dot_command, None, ".help"),
        "help_join": capture(repl.handle_dot_command, None, ".help join"),
        "help_two_words": capture(repl.handle_dot_command, None, ".help foreign key"),
        "help_none": capture(repl.handle_dot_command, None, ".help zzzz"),
        "prompt_main": repl.prompt_for(FakeBackend("main", False)),
        "prompt_txn": repl.prompt_for(FakeBackend("college", True)),
        "result_table": capture(repl.print_result, Result(["id", "naam"], [[1, "Ravi"], [2, None]], "2 row(s)")),
        "result_message": capture(repl.print_result, Result(message="Table 't' ban gaya (1 columns)")),
        "result_error": capture(repl.print_result, Result(error="[Execution Galti] Table 'x' exist nahi karta")),
        "result_empty": capture(repl.print_result, Result(["a"], [], "0 row(s)")),
        "result_unicode": capture(repl.print_result, Result(["n"], [[chr(0xE9) + chr(0x1F600)]], "1 row(s)")),
    }
    sys.__stdout__.write(json.dumps(samples))


def run_child(mode):
    env = {k: v for k, v in os.environ.items() if not k.startswith("MERADB_") and k != "NO_COLOR"}
    env.update(PYTHONIOENCODING="utf-8", PYTHONPATH=str(ROOT))
    if mode == "plain":
        env["NO_COLOR"] = "1"
    else:
        env["TERM"] = "xterm"  # makes repl.py trust ANSI on Windows too
    done = subprocess.run([sys.executable, __file__, "--child", mode], capture_output=True, env=env, cwd=str(ROOT), check=True)
    return json.loads(done.stdout.decode("utf-8"))


def literal(text):
    """A C++ string literal (one source line per text line, adjacent literals concatenate)."""
    pieces = []
    for line in text.split("\n"):
        out = []
        for ch in line:
            if ch == "\\":
                out.append("\\\\")
            elif ch == '"':
                out.append('\\"')
            elif ch == "\r":
                out.append("\\r")
            elif ch == "\x1b":
                out.append("\\x1b")
            elif ch == "\t":
                out.append("\\t")
            elif ord(ch) < 32:
                out.append("\\%03o" % ord(ch))  # octal: at most three digits, so a following digit is never swallowed
            else:
                out.append(ch)
        pieces.append("".join(out))
    return "\n        ".join('"%s%s"' % (p, "\\n" if i < len(pieces) - 1 else "") for i, p in enumerate(pieces))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--child")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()
    if args.child:
        child(args.child)
        return
    plain, color = run_child("plain"), run_child("color")
    assert plain.keys() == color.keys()
    lines = [
        "// cpp/tests/golden_shell.h -- GENERATED by gen_shell_golden.py from meradb/repl.py. Do not edit by hand.",
        "// Each sample exists twice: colour off (a pipe) and colour on (a terminal).",
        "#pragma once",
        "#include <stdexcept>",
        "#include <string>",
        "",
        "namespace golden_shell {",
        "",
        "struct Sample {",
        "    const char* name;",
        "    bool color;",
        "    const char* text;",
        "};",
        "",
        "inline const Sample* samples(int& count) {",
        "    static const Sample all[] = {",
    ]
    total = 0
    for name in plain:
        for flag, data in (("false", plain), ("true", color)):
            lines.append('        {"%s", %s,\n        %s},' % (name, flag, literal(data[name])))
            total += 1
    lines += [
        "    };",
        f"    count = {total};",
        "    return all;",
        "}",
        "",
        "// The sample called `name`, rendered with colour on or off.",
        "inline std::string get(const std::string& name, bool color) {",
        "    int count = 0;",
        "    const Sample* all = samples(count);",
        "    for (int i = 0; i < count; ++i)",
        "        if (name == all[i].name && all[i].color == color) return all[i].text;",
        '    throw std::runtime_error("no golden shell sample " + name);',
        "}",
        "",
        "}  // namespace golden_shell",
        "",
    ]
    args.out.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {args.out} ({total} samples)")


if __name__ == "__main__":
    main()
