"""
Regenerates cpp/tests/golden_help.h: what `python -m meradb COMMAND --help` prints
(COLUMNS pinned to 80) for every subcommand, with the data-folder default set
through MERADB_DATA to a short and to a long path (the long one wraps the help line).

    python cpp/tests/gen_help_golden.py
"""
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = Path(__file__).with_name("golden_help.h")
COMMANDS = ["server", "start", "stop", "status", "shell", "workbench", "run"]
FOLDERS = [
    "/srv/mdb",
    "/var/lib/mera db/data folder/with a rather long path name/x",
]


def help_text(command, folder):
    env = {k: v for k, v in os.environ.items() if not k.startswith("MERADB_")}
    env.update(COLUMNS="80", MERADB_DATA=folder, PYTHONIOENCODING="utf-8")
    r = subprocess.run([sys.executable, "-m", "meradb", command, "--help"], capture_output=True, env=env,
                       cwd=str(ROOT), timeout=60, check=True)
    return r.stdout.decode("utf-8").replace("\r\n", "\n")


lines = [
    "// cpp/tests/golden_help.h -- GENERATED by gen_help_golden.py from `python -m meradb COMMAND --help`",
    "// (COLUMNS=80). Do not edit by hand.",
    "#pragma once",
    "",
    "namespace golden_help {",
    "",
    "struct Case {",
    "    const char* command;",
    "    const char* dataDir;",
    "    const char* text;",
    "};",
    "",
    "inline const Case* cases(int& count) {",
    "    static const Case all[] = {",
]
total = 0
for folder in FOLDERS:
    for command in COMMANDS:
        text = help_text(command, folder)
        assert ')HELP"' not in text
        lines.append('        {"%s", "%s", R"HELP(%s)HELP"},' % (command, folder, text))
        total += 1
lines += [
    "    };",
    "    count = %d;" % total,
    "    return all;",
    "}",
    "",
    "}  // namespace golden_help",
    "",
]
OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
print("wrote", OUT, total, "cases")
