# cpp/tests/gen_shell_help.py
"""
Regenerates cpp/src/shell_help_data.inc: the `.help` keyword reference and the quick examples, copied from
meradb/repl.py (HELP_REFERENCE and EXAMPLES_HELP) so the C++ shell never drifts from the Python wording.

    python cpp/tests/gen_shell_help.py
"""
import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUT = ROOT / "cpp" / "src" / "shell_help_data.inc"


def literal(text):
    out = []
    for ch in text:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ord(ch) < 32 or ord(ch) > 126:
            raise SystemExit(f"non-ASCII or control character {ch!r} in the help text: extend the generator")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()
    sys.path.insert(0, str(ROOT))
    from meradb import repl

    lines = [
        "// cpp/src/shell_help_data.inc -- GENERATED by cpp/tests/gen_shell_help.py from meradb/repl.py. Do not edit by hand.",
        "// Included once, by repl_text.cpp, inside namespace meradb::repl.",
        "",
        "const std::vector<HelpCategory>& helpReference() {",
        "    static const std::vector<HelpCategory> data = {",
    ]
    for category, rows in repl.HELP_REFERENCE:
        lines.append(f"        {{{literal(category)},")
        lines.append("         {")
        for keyword, sql, desc in rows:
            lines.append(f"             {{{literal(keyword)}, {literal(sql)}, {literal(desc)}}},")
        lines.append("         }},")
    lines += ["    };", "    return data;", "}", "", "const char* examplesHelp() {",
              f"    return {literal(repl.EXAMPLES_HELP)};", "}", ""]
    args.out.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
