# cpp/tests/gen_shell_transcripts.py
"""
Regenerates cpp/tests/golden_transcripts.h: for every script in shell_scripts.py, what `python -m meradb
shell --local` prints (after the banner) when the script is piped into it. The C++ unit tests replay the same
input through repl::run and compare.

    python cpp/tests/gen_shell_transcripts.py
"""
import argparse
import os
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from gen_shell_golden import literal  # noqa: E402
from shell_scripts import SCRIPTS  # noqa: E402

ROOT = HERE.parents[1]
DEFAULT_OUT = HERE / "golden_transcripts.h"
BANNER_END = "se khatam hote hain\n\n"  # the last banner line, then the blank line the shell prints


def python_shell(script):
    """What the Python shell prints for `script` on stdin, with CRLF normalised and the banner cut off."""
    env = {k: v for k, v in os.environ.items() if not k.startswith("MERADB_") and k != "NO_COLOR"}
    env.update(PYTHONIOENCODING="utf-8", PYTHONPATH=str(ROOT), NO_COLOR="1")
    with tempfile.TemporaryDirectory() as data:
        done = subprocess.run([sys.executable, "-m", "meradb", "shell", "--local", "--data", data],
                              input=script.encode("utf-8"), capture_output=True, env=env, cwd=str(ROOT), timeout=120)
    assert done.returncode == 0, (done.returncode, done.stderr)
    text = done.stdout.decode("utf-8").replace("\r\n", "\n")
    head, marker, rest = text.partition(BANNER_END)
    assert marker, "banner end not found"
    return rest


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()
    lines = [
        "// cpp/tests/golden_transcripts.h -- GENERATED by gen_shell_transcripts.py: what the Python shell prints (after",
        "// its banner) for each script in shell_scripts.py. Do not edit by hand.",
        "#pragma once",
        "#include <stdexcept>",
        "#include <string>",
        "",
        "namespace golden_transcripts {",
        "",
        "struct Transcript {",
        "    const char* name;",
        "    std::string input;",
        "    std::string output;",
        "};",
        "",
        "inline const Transcript* all(int& count) {",
        "    static const Transcript data[] = {",
    ]
    for name, script in SCRIPTS.items():
        lines.append('        {"%s",\n        %s,\n        %s},' % (name, literal(script) if script else '""', literal(python_shell(script))))
    lines += [
        "    };",
        f"    count = {len(SCRIPTS)};",
        "    return data;",
        "}",
        "",
        "inline const Transcript& get(const std::string& name) {",
        "    int count = 0;",
        "    const Transcript* data = all(count);",
        "    for (int i = 0; i < count; ++i)",
        "        if (name == data[i].name) return data[i];",
        '    throw std::runtime_error("no golden transcript " + name);',
        "}",
        "",
        "}  // namespace golden_transcripts",
        "",
    ]
    args.out.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {args.out} ({len(SCRIPTS)} transcripts)")


if __name__ == "__main__":
    main()
