#!/usr/bin/env python3
"""Regenerates cpp/tests/golden_highlight.h: what meradb/highlight.py returns for many lines (byte offsets)."""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from meradb.aggregates import ALIASES  # noqa: E402
from meradb.datatypes import TYPE_ALIASES  # noqa: E402
from meradb.highlight import spans  # noqa: E402
from meradb.tokenizer import KEYWORDS  # noqa: E402

EDGE = [
    "", "   ", "-- only a comment", "x -- c", "'a'", "'a''b'", "'a'''", "'a''", "'", "''",
    "a<=b>=c!=d<>e", "a!b", "1.5.5", "1..2", "x1 1x _1 a_b", "12 3.5 1abc 7.x", "(()", "DIKHAO\t*\tSE\tt",
    "dikhao Dikhao DIKHAO", "SACH sach JhOoTh KHALI khali", "gino (*)", "gino   (", "count(*) COUNT (x)",
    "max(a) MAX b", "x = 'it''s' -- note", "'é' é -- ü", "12é 3", "é" "12", "1.5é",
    " DIKHAO", "DIKHAO (", "x;y,z.w", "a % b / c + d - e * f",
]

# Lines whose Python result depends on Unicode-aware \b / \d (ruling R11); none so far.
DROP = set()


def corpus():
    seen = []

    def add(line):
        if line not in seen and line not in DROP:
            seen.append(line)

    for name in ("demo.mdb", "rdbms_lab_coverage.mdb"):
        text = (ROOT / "examples" / name).read_text(encoding="utf-8-sig")
        for line in text.split("\n"):
            add(line.rstrip("\r"))
    for line in EDGE:
        add(line)
    for word in sorted(set(KEYWORDS) | set(TYPE_ALIASES) | set(ALIASES)):
        for w in (word, word.lower()):
            add(w)
            add(w + "(")
            add(w + " (")
    return seen


def cpp_string(text):
    out = []
    for b in text.encode("utf-8"):
        if b in (34, 92, 63) or not 32 <= b < 127:
            out.append("\\%03o" % b)
        else:
            out.append(chr(b))
    return '"' + "".join(out) + '"'


def byte_spans(line):
    return ";".join(
        "%d,%d,%s" % (len(line[:s].encode("utf-8")), len(line[:e].encode("utf-8")), kind) for s, e, kind in spans(line)
    )


def main():
    lines = ["// cpp/tests/golden_highlight.h -- GENERATED by gen_highlight_golden.py from meradb/highlight.py; do not edit.",
             "#pragma once", "", "struct HighlightCase {", "    const char* line;", "    const char* spans;  // \"start,end,kind;...\" (byte offsets)", "};", "",
             "inline const HighlightCase kHighlightCases[] = {"]
    cases = corpus()
    for line in cases:
        lines.append("    {%s, %s}," % (cpp_string(line), cpp_string(byte_spans(line))))
    lines.append("};")
    (ROOT / "cpp" / "tests" / "golden_highlight.h").write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print("wrote %d cases" % len(cases))


if __name__ == "__main__":
    main()
