# cpp/tests/gen_word_table.py
"""
Regenerates cpp/src/word_table.inc: the code points Python's re module counts as word characters (the word class) in a str
pattern, i.e. str.isalnum() or '_'. Combining marks, symbols (such as the euro sign) and spaces are not word
characters; letters and numeric characters of every script are. Used by pytext::isWordChar for the highlighter's
\b checks.

    python cpp/tests/gen_word_table.py            # rewrite the file
    python cpp/tests/gen_word_table.py --check    # exit 1 if it differs from a fresh run
"""
import re
import sys
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "cpp" / "src" / "word_table.inc"
WORD = re.compile(r"\w")


def build():
    ranges = []
    start = None
    for cp in range(0x110000):
        word = not 0xD800 <= cp <= 0xDFFF and bool(WORD.match(chr(cp)))
        if word and start is None:
            start = cp
        elif not word and start is not None:
            ranges.append((start, cp - 1))
            start = None
    if start is not None:
        ranges.append((start, 0x10FFFF))
    lines = [
        "// cpp/src/word_table.inc -- GENERATED by cpp/tests/gen_word_table.py. Do not edit by hand.",
        "// Python %d.%d / Unicode %s: the code points matched by the re word class (str.isalnum() or '_') as sorted inclusive ranges."
        % (sys.version_info[0], sys.version_info[1], unicodedata.unidata_version),
        "const WordRange kWordRanges[] = {",
    ]
    row = []
    for lo, hi in ranges:
        row.append("{0x%04X, 0x%04X}" % (lo, hi))
        if len(row) == 6:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    text = build()
    if "--check" in sys.argv:
        sys.exit(0 if OUT.exists() and OUT.read_text(encoding="utf-8") == text else 1)
    OUT.write_text(text, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
