// cpp/tests/golden_help.h -- GENERATED by gen_help_golden.py from `python -m meradb COMMAND --help`
// (COLUMNS=80). Do not edit by hand.
#pragma once

namespace golden_help {

struct Case {
    const char* command;
    const char* dataDir;
    const char* text;
};

inline const Case* cases(int& count) {
    static const Case all[] = {
        {"server", "/srv/mdb", R"HELP(usage: meradb server [-h] [-D DATA] [--host HOST] [--port PORT]
                     [--password PASSWORD] [-v]

options:
  -h, --help            show this help message and exit
  -D DATA, --data DATA  data folder (default: /srv/mdb, ya MERADB_DATA)
  --host HOST           kis address par suno (default 127.0.0.1; LAN ke liye
                        0.0.0.0)
  --port PORT           TCP port (default 6372, ya MERADB_PORT)
  --password PASSWORD   clients ko ye password dena hoga (ya MERADB_PASSWORD)
  -v, --verbose         har query log karo
)HELP"},
        {"start", "/srv/mdb", R"HELP(usage: meradb start [-h] [-D DATA] [--host HOST] [--port PORT]
                    [--password PASSWORD] [-v]

options:
  -h, --help            show this help message and exit
  -D DATA, --data DATA  data folder (default: /srv/mdb, ya MERADB_DATA)
  --host HOST           kis address par suno (default 127.0.0.1; LAN ke liye
                        0.0.0.0)
  --port PORT           TCP port (default 6372, ya MERADB_PORT)
  --password PASSWORD   clients ko ye password dena hoga (ya MERADB_PASSWORD)
  -v, --verbose         har query log karo
)HELP"},
        {"stop", "/srv/mdb", R"HELP(usage: meradb stop [-h] [-D DATA] [-W] [--force]

options:
  -h, --help            show this help message and exit
  -D DATA, --data DATA  data folder (default: /srv/mdb, ya MERADB_DATA)
  -W, --password        password poocho (ya MERADB_PASSWORD)
  --force               agar normal shutdown na ho to process kill karo
)HELP"},
        {"status", "/srv/mdb", R"HELP(usage: meradb status [-h] [-D DATA] [-W]

options:
  -h, --help            show this help message and exit
  -D DATA, --data DATA  data folder (default: /srv/mdb, ya MERADB_DATA)
  -W, --password        password poocho (ya MERADB_PASSWORD)
)HELP"},
        {"shell", "/srv/mdb", R"HELP(usage: meradb shell [-h] [-D DATA] [-H HOST] [-p PORT] [-d DATABASE] [-W]
                    [-U USER] [--local]

options:
  -h, --help            show this help message and exit
  -D DATA, --data DATA  data folder (default: /srv/mdb, ya MERADB_DATA)
  -H HOST, --host HOST  server ka address (default 127.0.0.1, ya MERADB_HOST)
  -p PORT, --port PORT  server ka port (default 6372, ya MERADB_PORT)
  -d DATABASE, --database DATABASE
                        shuru mein ye database istemal karo
  -W, --password        password poocho (ya MERADB_PASSWORD)
  -U USER, --user USER  is USERNAME se login karo (ya MERADB_USER) --
                        privileges ke saath, server-wide password ki jagah
  --local               server ke bina, seedha data folder kholo
)HELP"},
        {"workbench", "/srv/mdb", R"HELP(usage: meradb workbench [-h] [-D DATA] [-H HOST] [-p PORT] [-d DATABASE] [-W]
                        [-U USER] [--local]

options:
  -h, --help            show this help message and exit
  -D DATA, --data DATA  data folder (default: /srv/mdb, ya MERADB_DATA)
  -H HOST, --host HOST  server ka address (default 127.0.0.1, ya MERADB_HOST)
  -p PORT, --port PORT  server ka port (default 6372, ya MERADB_PORT)
  -d DATABASE, --database DATABASE
                        shuru mein ye database istemal karo
  -W, --password        password poocho (ya MERADB_PASSWORD)
  -U USER, --user USER  is USERNAME se login karo (ya MERADB_USER) --
                        privileges ke saath, server-wide password ki jagah
  --local               server ke bina, seedha data folder kholo
)HELP"},
        {"run", "/srv/mdb", R"HELP(usage: meradb run [-h] [-D DATA] [-H HOST] [-p PORT] [-d DATABASE] [-W]
                  [-U USER] [--local]
                  files [files ...]

positional arguments:
  files                 script files

options:
  -h, --help            show this help message and exit
  -D DATA, --data DATA  data folder (default: /srv/mdb, ya MERADB_DATA)
  -H HOST, --host HOST  server ka address (default 127.0.0.1, ya MERADB_HOST)
  -p PORT, --port PORT  server ka port (default 6372, ya MERADB_PORT)
  -d DATABASE, --database DATABASE
                        shuru mein ye database istemal karo
  -W, --password        password poocho (ya MERADB_PASSWORD)
  -U USER, --user USER  is USERNAME se login karo (ya MERADB_USER) --
                        privileges ke saath, server-wide password ki jagah
  --local               server ke bina, seedha data folder kholo
)HELP"},
        {"server", "/var/lib/mera db/data folder/with a rather long path name/x", R"HELP(usage: meradb server [-h] [-D DATA] [--host HOST] [--port PORT]
                     [--password PASSWORD] [-v]

options:
  -h, --help            show this help message and exit
  -D DATA, --data DATA  data folder (default: /var/lib/mera db/data
                        folder/with a rather long path name/x, ya MERADB_DATA)
  --host HOST           kis address par suno (default 127.0.0.1; LAN ke liye
                        0.0.0.0)
  --port PORT           TCP port (default 6372, ya MERADB_PORT)
  --password PASSWORD   clients ko ye password dena hoga (ya MERADB_PASSWORD)
  -v, --verbose         har query log karo
)HELP"},
        {"start", "/var/lib/mera db/data folder/with a rather long path name/x", R"HELP(usage: meradb start [-h] [-D DATA] [--host HOST] [--port PORT]
                    [--password PASSWORD] [-v]

options:
  -h, --help            show this help message and exit
  -D DATA, --data DATA  data folder (default: /var/lib/mera db/data
                        folder/with a rather long path name/x, ya MERADB_DATA)
  --host HOST           kis address par suno (default 127.0.0.1; LAN ke liye
                        0.0.0.0)
  --port PORT           TCP port (default 6372, ya MERADB_PORT)
  --password PASSWORD   clients ko ye password dena hoga (ya MERADB_PASSWORD)
  -v, --verbose         har query log karo
)HELP"},
        {"stop", "/var/lib/mera db/data folder/with a rather long path name/x", R"HELP(usage: meradb stop [-h] [-D DATA] [-W] [--force]

options:
  -h, --help            show this help message and exit
  -D DATA, --data DATA  data folder (default: /var/lib/mera db/data
                        folder/with a rather long path name/x, ya MERADB_DATA)
  -W, --password        password poocho (ya MERADB_PASSWORD)
  --force               agar normal shutdown na ho to process kill karo
)HELP"},
        {"status", "/var/lib/mera db/data folder/with a rather long path name/x", R"HELP(usage: meradb status [-h] [-D DATA] [-W]

options:
  -h, --help            show this help message and exit
  -D DATA, --data DATA  data folder (default: /var/lib/mera db/data
                        folder/with a rather long path name/x, ya MERADB_DATA)
  -W, --password        password poocho (ya MERADB_PASSWORD)
)HELP"},
        {"shell", "/var/lib/mera db/data folder/with a rather long path name/x", R"HELP(usage: meradb shell [-h] [-D DATA] [-H HOST] [-p PORT] [-d DATABASE] [-W]
                    [-U USER] [--local]

options:
  -h, --help            show this help message and exit
  -D DATA, --data DATA  data folder (default: /var/lib/mera db/data
                        folder/with a rather long path name/x, ya MERADB_DATA)
  -H HOST, --host HOST  server ka address (default 127.0.0.1, ya MERADB_HOST)
  -p PORT, --port PORT  server ka port (default 6372, ya MERADB_PORT)
  -d DATABASE, --database DATABASE
                        shuru mein ye database istemal karo
  -W, --password        password poocho (ya MERADB_PASSWORD)
  -U USER, --user USER  is USERNAME se login karo (ya MERADB_USER) --
                        privileges ke saath, server-wide password ki jagah
  --local               server ke bina, seedha data folder kholo
)HELP"},
        {"workbench", "/var/lib/mera db/data folder/with a rather long path name/x", R"HELP(usage: meradb workbench [-h] [-D DATA] [-H HOST] [-p PORT] [-d DATABASE] [-W]
                        [-U USER] [--local]

options:
  -h, --help            show this help message and exit
  -D DATA, --data DATA  data folder (default: /var/lib/mera db/data
                        folder/with a rather long path name/x, ya MERADB_DATA)
  -H HOST, --host HOST  server ka address (default 127.0.0.1, ya MERADB_HOST)
  -p PORT, --port PORT  server ka port (default 6372, ya MERADB_PORT)
  -d DATABASE, --database DATABASE
                        shuru mein ye database istemal karo
  -W, --password        password poocho (ya MERADB_PASSWORD)
  -U USER, --user USER  is USERNAME se login karo (ya MERADB_USER) --
                        privileges ke saath, server-wide password ki jagah
  --local               server ke bina, seedha data folder kholo
)HELP"},
        {"run", "/var/lib/mera db/data folder/with a rather long path name/x", R"HELP(usage: meradb run [-h] [-D DATA] [-H HOST] [-p PORT] [-d DATABASE] [-W]
                  [-U USER] [--local]
                  files [files ...]

positional arguments:
  files                 script files

options:
  -h, --help            show this help message and exit
  -D DATA, --data DATA  data folder (default: /var/lib/mera db/data
                        folder/with a rather long path name/x, ya MERADB_DATA)
  -H HOST, --host HOST  server ka address (default 127.0.0.1, ya MERADB_HOST)
  -p PORT, --port PORT  server ka port (default 6372, ya MERADB_PORT)
  -d DATABASE, --database DATABASE
                        shuru mein ye database istemal karo
  -W, --password        password poocho (ya MERADB_PASSWORD)
  -U USER, --user USER  is USERNAME se login karo (ya MERADB_USER) --
                        privileges ke saath, server-wide password ki jagah
  --local               server ke bina, seedha data folder kholo
)HELP"},
    };
    count = 14;
    return all;
}

}  // namespace golden_help
