// cpp/tests/test_repl_text.cpp -- the shell's words, compared with what repl.py produces
// (golden_shell.h is generated by gen_shell_golden.py).
#include <catch2/catch_test_macros.hpp>
#include "golden_shell.h"
#include "meradb/repl_text.h"
#include <chrono>
#include <sstream>

using namespace meradb;

TEST_CASE("shell help: the full .help text matches Python, plain and coloured", "[shell]") {
    for (bool color : {false, true}) {
        INFO((color ? "colour" : "plain"));
        CHECK(repl::fullHelp(term::Style(color)) + "\n" == golden_shell::get("help_full", color));
    }
}

TEST_CASE("shell help: filtered references match Python", "[shell]") {
    for (bool color : {false, true}) {
        INFO((color ? "colour" : "plain"));
        const term::Style style(color);
        CHECK(repl::renderReference(style, "join") + "\n" == golden_shell::get("help_join", color));
        CHECK(repl::renderReference(style, "foreign key") + "\n" == golden_shell::get("help_two_words", color));
        CHECK(repl::renderReference(style, "zzzz") + "\n" == golden_shell::get("help_none", color));
    }
}

TEST_CASE("shell help: the query is stripped and lower-cased", "[shell]") {
    const term::Style plain;
    CHECK(repl::renderReference(plain, "  JOIN \t") == repl::renderReference(plain, "join"));
    CHECK(repl::renderReference(plain, "") == repl::renderReference(plain));
    CHECK(repl::renderReference(plain, "   ") == repl::renderReference(plain));  // blank means everything
    CHECK(repl::renderReference(plain, "Q?") == "'q?' ke liye kuch nahi mila. Poora reference ke liye sirf .help likho.");
}

TEST_CASE("shell help: the reference data has every category Python has", "[shell]") {
    const auto& data = repl::helpReference();
    REQUIRE_FALSE(data.empty());
    CHECK(data.front().name == "Databases");
    CHECK(data.back().name == "Stored procedures");
    std::size_t rows = 0;
    for (const auto& category : data) rows += category.rows.size();
    CHECK(rows > 60);
    CHECK(std::string(repl::examplesHelp()).rfind("Quick examples (full reference: docs/LANGUAGE.md):\n", 0) == 0);
}

TEST_CASE("shell banner matches Python, plain and coloured", "[shell]") {
    for (bool color : {false, true}) {
        INFO((color ? "colour" : "plain"));
        std::ostringstream out;
        repl::printBanner(out, term::Style(color), "1.0.0", "local (/data/x)", 0);
        CHECK(out.str() == golden_shell::get("banner", color));
        std::ostringstream server;
        repl::printBanner(server, term::Style(color), "1.0.0", "127.0.0.1:6372", 0);
        CHECK(server.str() == golden_shell::get("banner_server", color));
    }
}

TEST_CASE("shell banner reveal pauses only when asked to", "[shell]") {
    std::ostringstream out;
    const auto start = std::chrono::steady_clock::now();
    repl::printBanner(out, term::Style::none(), "1.0.0", "x", 5);  // 12 logo/wordmark lines x 5 ms
    const auto elapsed = std::chrono::steady_clock::now() - start;
    CHECK(elapsed >= std::chrono::milliseconds(50));
    CHECK(out.str().find("connected: x") != std::string::npos);
}

TEST_CASE("shell prompts match Python", "[shell]") {
    for (bool color : {false, true}) {
        INFO((color ? "colour" : "plain"));
        const term::Style style(color);
        CHECK(repl::promptFor(style, "main", false) == golden_shell::get("prompt_main", color));
        CHECK(repl::promptFor(style, "college", true) == golden_shell::get("prompt_txn", color));
    }
    CHECK(std::string(repl::kContinuationPrompt) == "      ...> ");
}
