// cpp/tests/test_catalog.cpp
#include <catch2/catch_test_macros.hpp>
#include "meradb/catalog.h"
#include "meradb/errors.h"
#include "test_util.h"
#include <filesystem>
#include <fstream>

using namespace meradb;
using meradb_test::TempDir;

namespace {

// Exactly what meradb/catalog.py (json.dump(..., indent=2)) writes for a
// two-table database with a view -- generated by the Python engine.
const char* kPythonCatalog = R"({
  "tables": {
    "students": {
      "name": "students",
      "columns": [
        {
          "name": "id",
          "type_name": "INT",
          "primary_key": true,
          "not_null": false,
          "unique": false,
          "default": null,
          "max_length": null,
          "ref_table": null,
          "ref_column": null,
          "check": null
        },
        {
          "name": "naam",
          "type_name": "TEXT",
          "primary_key": false,
          "not_null": true,
          "unique": false,
          "default": "Ravi\u00e9",
          "max_length": 20,
          "ref_table": null,
          "ref_column": null,
          "check": null
        },
        {
          "name": "dob",
          "type_name": "DATE",
          "primary_key": false,
          "not_null": false,
          "unique": false,
          "default": "2004-05-06",
          "max_length": null,
          "ref_table": null,
          "ref_column": null,
          "check": null
        },
        {
          "name": "cgpa",
          "type_name": "FLOAT",
          "primary_key": false,
          "not_null": false,
          "unique": false,
          "default": 7.5,
          "max_length": null,
          "ref_table": null,
          "ref_column": null,
          "check": "cgpa >= 0"
        },
        {
          "name": "ok",
          "type_name": "BOOL",
          "primary_key": false,
          "not_null": false,
          "unique": false,
          "default": true,
          "max_length": null,
          "ref_table": null,
          "ref_column": null,
          "check": null
        }
      ],
      "composite_unique": [
        [
          "naam",
          "dob"
        ]
      ],
      "composite_pk": null
    },
    "enroll": {
      "name": "enroll",
      "columns": [
        {
          "name": "sid",
          "type_name": "INT",
          "primary_key": false,
          "not_null": false,
          "unique": false,
          "default": null,
          "max_length": null,
          "ref_table": "students",
          "ref_column": "id",
          "check": null
        },
        {
          "name": "cid",
          "type_name": "INT",
          "primary_key": false,
          "not_null": false,
          "unique": false,
          "default": -3,
          "max_length": null,
          "ref_table": null,
          "ref_column": null,
          "check": null
        }
      ],
      "composite_unique": [],
      "composite_pk": [
        "sid",
        "cid"
      ]
    }
  },
  "views": {
    "toppers": "DIKHAO naam SE students JAHAN cgpa > 9;"
  },
  "triggers": {},
  "procedures": {}
})";

void writeText(const std::string& path, const std::string& text) {
    std::ofstream out(path);
    out << text;
}

}  // namespace

TEST_CASE("Catalog creates and persists a table schema", "[catalog]") {
    TempDir dir;
    {
        Catalog cat(dir.str());
        TableSchema schema;
        schema.name = "students";
        Column id; id.name = "id"; id.typeName = "INT"; id.primaryKey = true;
        Column naam; naam.name = "naam"; naam.typeName = "TEXT"; naam.notNull = true;
        schema.columns = {id, naam};
        cat.add(schema);
    }
    Catalog cat2(dir.str());
    REQUIRE(cat2.find("students") != nullptr);
    REQUIRE(cat2.get("students").columns.size() == 2);
    REQUIRE(cat2.get("students").columns[0].primaryKey);
    REQUIRE(cat2.get("students").columns[1].notNull);
    REQUIRE_FALSE(cat2.get("students").columns[1].defaultValue.has_value());
}

TEST_CASE("Catalog::get throws ExecutionError for unknown table", "[catalog]") {
    TempDir dir;
    Catalog cat(dir.str());
    REQUIRE(cat.find("nope") == nullptr);
    try {
        cat.get("nope");
        FAIL("expected ExecutionError");
    } catch (const ExecutionError& e) {
        REQUIRE(e.message() == "Table 'nope' exist nahi karta");
    }
}

TEST_CASE("Catalog persists and reloads views", "[catalog]") {
    TempDir dir;
    {
        Catalog cat(dir.str());
        cat.addView("toppers", "DIKHAO naam SE students JAHAN cgpa > 9;");
    }
    Catalog cat2(dir.str());
    REQUIRE(cat2.views.count("toppers") == 1);
    REQUIRE(cat2.views.at("toppers").find("DIKHAO") == 0);
    cat2.removeView("toppers");
    Catalog cat3(dir.str());
    REQUIRE(cat3.views.empty());
}

TEST_CASE("TableSchema::indexOf resolves column position and rejects unknowns", "[catalog]") {
    TableSchema schema;
    schema.name = "t";
    Column a; a.name = "a"; schema.columns.push_back(a);
    Column b; b.name = "b"; schema.columns.push_back(b);
    REQUIRE(schema.indexOf("b") == 1);
    REQUIRE(schema.getColumn("a").name == "a");
    try {
        schema.indexOf("z");
        FAIL("expected ExecutionError");
    } catch (const ExecutionError& e) {
        REQUIRE(e.message() == "Table 't' mein column 'z' nahi hai");
    }
}

TEST_CASE("Catalog::save writes atomically (no partial file left behind)", "[catalog]") {
    TempDir dir;
    Catalog cat(dir.str());
    TableSchema schema; schema.name = "t";
    cat.add(schema);
    cat.save();  // second save must replace the existing catalog.json
    REQUIRE(std::filesystem::exists(dir.path() / "catalog.json"));
    REQUIRE_FALSE(std::filesystem::exists(dir.path() / "catalog.json.tmp"));
}

TEST_CASE("Column defaults survive a catalog save/reload with their types", "[catalog]") {
    TempDir dir;
    {
        Catalog cat(dir.str());
        TableSchema s; s.name = "t";
        Column d; d.name = "dob"; d.typeName = "DATE"; d.defaultValue = coerce(Value(std::string("2004-05-06")), "DATE", "dob");
        Column n; n.name = "marks"; n.typeName = "INT"; n.defaultValue = Value(int64_t{42});
        Column f; f.name = "cgpa"; f.typeName = "FLOAT"; f.defaultValue = Value(5.0);
        Column b; b.name = "ok"; b.typeName = "BOOL"; b.defaultValue = Value(false);
        Column x; x.name = "naam"; x.typeName = "TEXT"; x.defaultValue = Value(std::string("Ravi"));
        s.columns = {d, n, f, b, x};
        cat.add(s);
    }
    Catalog cat2(dir.str());
    const auto& cols = cat2.get("t").columns;
    REQUIRE(std::get<Date>(cols[0].defaultValue->data) == parseDate("2004-05-06"));
    REQUIRE(std::get<int64_t>(cols[1].defaultValue->data) == 42);
    REQUIRE(std::get<double>(cols[2].defaultValue->data) == 5.0);  // 5.0 stays a FLOAT, not INT 5
    REQUIRE(std::get<bool>(cols[3].defaultValue->data) == false);
    REQUIRE(std::get<std::string>(cols[4].defaultValue->data) == "Ravi");
}

TEST_CASE("Catalog reads a catalog.json written by the Python engine", "[catalog]") {
    TempDir dir;
    writeText(dir.file("catalog.json"), kPythonCatalog);
    Catalog cat(dir.str());

    // insertion order is kept, like a Python dict
    std::vector<std::string> names;
    for (const auto& [name, schema] : cat.tables) names.push_back(name);
    REQUIRE(names == std::vector<std::string>{"students", "enroll"});

    const auto& s = cat.get("students");
    REQUIRE(s.columnNames() == std::vector<std::string>{"id", "naam", "dob", "cgpa", "ok"});
    REQUIRE(s.types() == std::vector<std::string>{"INT", "TEXT", "DATE", "FLOAT", "BOOL"});
    REQUIRE(std::get<std::string>(s.columns[1].defaultValue->data) == "Ravi\xC3\xA9");
    REQUIRE(s.columns[1].maxLength == 20);
    REQUIRE(std::get<Date>(s.columns[2].defaultValue->data).isoFormat() == "2004-05-06");
    REQUIRE(std::get<double>(s.columns[3].defaultValue->data) == 7.5);
    REQUIRE(s.columns[3].check == std::string("cgpa >= 0"));
    REQUIRE(std::get<bool>(s.columns[4].defaultValue->data) == true);
    REQUIRE(s.compositeUnique == std::vector<std::vector<std::string>>{{"naam", "dob"}});
    REQUIRE_FALSE(s.compositePk.has_value());

    const auto& e = cat.get("enroll");
    REQUIRE(e.columns[0].refTable == std::string("students"));
    REQUIRE(e.columns[0].refColumn == std::string("id"));
    REQUIRE(std::get<int64_t>(e.columns[1].defaultValue->data) == -3);
    REQUIRE(e.compositePk == std::vector<std::string>{"sid", "cid"});
    REQUIRE(cat.views.at("toppers") == "DIKHAO naam SE students JAHAN cgpa > 9;");
}

TEST_CASE("Catalog::save output is identical to what Python writes", "[catalog]") {
    TempDir dir;
    writeText(dir.file("catalog.json"), kPythonCatalog);
    {
        Catalog cat(dir.str());
        cat.save();
    }
    REQUIRE(meradb_test::readText(dir.file("catalog.json")) == kPythonCatalog);
}

TEST_CASE("Catalog carries Phase 2 triggers/procedures through a save untouched", "[catalog]") {
    TempDir dir;
    writeText(dir.file("catalog.json"), R"({
  "tables": {},
  "views": {},
  "triggers": {"trg": {"timing": "BAAD", "event": "DAALO", "table": "t", "body_text": "x"}},
  "procedures": {"p": {"params": [["a", "INT"]], "body_text": "y"}}
})");
    {
        Catalog cat(dir.str());
        cat.addView("v", "DIKHAO 1;");
    }
    Catalog cat2(dir.str());
    REQUIRE(cat2.triggers["trg"]["timing"] == "BAAD");
    REQUIRE(cat2.procedures["p"]["params"][0][1] == "INT");
}

TEST_CASE("Catalog loads an old catalog.json without the newer keys", "[catalog]") {
    TempDir dir;
    writeText(dir.file("catalog.json"),
              R"({"tables": {"t": {"name": "t", "columns": [{"name": "a", "type_name": "INT", "primary_key": false,)"
              R"( "not_null": false, "unique": true, "default": null}]}}})");
    Catalog cat(dir.str());
    const auto& t = cat.get("t");
    REQUIRE(t.columns[0].isUnique());
    REQUIRE_FALSE(t.columns[0].maxLength.has_value());
    REQUIRE(t.compositeUnique.empty());
    REQUIRE(cat.views.empty());
}

TEST_CASE("Catalog::remove drops a table and keeps the others in order", "[catalog]") {
    TempDir dir;
    {
        Catalog cat(dir.str());
        for (const char* n : {"c", "a", "b"}) {
            TableSchema s; s.name = n;
            cat.add(s);
        }
        cat.remove("a");
        REQUIRE_THROWS_AS(cat.remove("a"), ExecutionError);
    }
    Catalog cat2(dir.str());
    std::vector<std::string> names;
    for (const auto& [name, schema] : cat2.tables) names.push_back(name);
    REQUIRE(names == std::vector<std::string>{"c", "b"});
    REQUIRE(cat2.tablePath("c") == (dir.path() / "c.tbl").string());
}
