#!/usr/bin/env python
"""Regenerates cpp/tests/golden_engine.h from the reference (Python) engine.

Every cpp/tests/golden/<group>_<name>.mdb is a script with ONE statement per
line. A line starting `@name:` runs on a restricted session for user `name`
that shares the script's Instance (created on first use); every other line
runs on the superuser session. Each script is run against a fresh Engine and the outcome of every
statement is recorded in a canonical text form; the C++ test replays the same
script and compares the outcome statement by statement, so the two engines are
checked against each other on messages, error wording, columns and rows.

Canonical form of one outcome:   C:<columns> R:<rows> M:<message> E:<error>
  columns joined by ',', rows by ';', cells by '|' (Python's format_value).

Run from anywhere:  python cpp/tests/golden/gen_golden.py
"""
import glob
import os
import re
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
sys.path.insert(0, ROOT)

from meradb.datatypes import format_value  # noqa: E402
from meradb.engine import Engine  # noqa: E402


def canonical(r) -> str:
    rows = ";".join("|".join(format_value(v) for v in row) for row in r.rows)
    return f"C:{','.join(r.columns)} R:{rows} M:{r.message} E:{r.error}"


def raw(text: str) -> str:
    assert ')MDB"' not in text
    return f'R"MDB({text})MDB"'


def main() -> None:
    out = [
        "// GENERATED by tests/golden/gen_golden.py from the Python reference engine. Do not edit.",
        "#pragma once",
        "#include <vector>",
        "",
        "namespace golden {",
        "struct Step { const char* sql; const char* expect; };",
        "struct Script { const char* group; const char* name; std::vector<Step> steps; };",
        "inline const std::vector<Script>& scripts() {",
        "    static const std::vector<Script> all = {",
    ]
    for path in sorted(glob.glob(os.path.join(HERE, "*.mdb"))):
        base = os.path.splitext(os.path.basename(path))[0]
        group, _, name = base.partition("_")
        with open(path, encoding="utf-8") as f:
            statements = [ln.strip() for ln in f if ln.strip()]
        with tempfile.TemporaryDirectory() as data:
            engine = Engine(data)
            sessions = {}
            out.append(f'        {{"{group}", "{name}", {{')
            for sql in statements:
                target, text = engine, sql
                m = re.match(r"^@(\w+):\s*(.*)$", sql)
                if m:
                    user, text = m.group(1), m.group(2)
                    if user not in sessions:
                        sessions[user] = Engine(engine.instance)  # shares the Instance (and its lock)
                        sessions[user].user = user
                    target = sessions[user]
                result = target.run_script(text)[-1]
                out.append(f"            {{{raw(sql)}, {raw(canonical(result))}}},")
            out.append("        }},")
    out += ["    };", "    return all;", "}", "}  // namespace golden", ""]
    target = os.path.join(HERE, "..", "golden_engine.h")
    with open(target, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    print("wrote", os.path.abspath(target))


if __name__ == "__main__":
    main()
