# cpp/cmake/embed_file.cmake -- cmake -DINPUT=<file> -DOUTPUT=<file.inc> -P embed_file.cmake
# Turns a text file into a C++ byte array so the workbench can show docs/LANGUAGE.md without finding it at run time.
if(EXISTS "${INPUT}")
  file(READ "${INPUT}" _hex HEX)
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_hex}")
  set(_present "true")
else()
  set(_bytes "")
  set(_present "false")
endif()
file(WRITE "${OUTPUT}"
  "// GENERATED by cmake/embed_file.cmake; do not edit.\n"
  "static const unsigned char kLanguageDocBytes[] = {${_bytes}0x00};\n"
  "static const bool kLanguageDocPresent = ${_present};\n")
