# cpp/cmake/patch_ftxui.cmake -- FTXUI 5.0's Windows input loop converts each UTF-16 unit of a key event on its own, so the
# two halves of an emoji are lost. This makes it pass the units through ftxui_patch::SurrogateJoiner
# (cpp/ftxui_patch/ftxui_win_input.h). Idempotent; included after FetchContent_MakeAvailable(ftxui), Windows only.
function(meradb_patch_ftxui_input source_dir patch_header)
  set(file "${source_dir}/src/ftxui/component/screen_interactive.cpp")
  if(NOT EXISTS "${file}")
    message(FATAL_ERROR "FTXUI source not found: ${file}")
  endif()
  configure_file("${patch_header}" "${source_dir}/src/ftxui/component/ftxui_win_input.h" COPYONLY)
  file(READ "${file}" text)
  if(text MATCHES "ftxui_win_input\\.h")
    return()
  endif()
  set(old_unit "          std::wstring wstring;\n          wstring += key_event.uChar.UnicodeChar;\n          for (auto it : to_string(wstring)) {")
  set(new_unit "          for (auto it : surrogate_joiner.push(static_cast<std::uint16_t>(key_event.uChar.UnicodeChar))) {")
  set(old_up "          if (key_event.bKeyDown == FALSE)\n            continue;")
  set(new_up "          if (!ftxui_patch::SurrogateJoiner::wantsKeyEvent(key_event.bKeyDown != FALSE, key_event.wVirtualKeyCode,\n                                                           static_cast<std::uint16_t>(key_event.uChar.UnicodeChar)))\n            continue;")
  set(old_parser"  auto parser = TerminalInputParser(out->Clone());\n")
  set(new_parser "  auto parser = TerminalInputParser(out->Clone());\n  ftxui_patch::SurrogateJoiner surrogate_joiner;\n")
  set(old_inc "#include \"ftxui/component/screen_interactive.hpp\"\n")
  set(new_inc "#include \"ftxui/component/screen_interactive.hpp\"\n#include \"ftxui_win_input.h\"\n")
  foreach(part up unit parser inc)
    string(FIND "${text}" "${old_${part}}" at)
    if(at EQUAL -1)
      message(FATAL_ERROR "FTXUI screen_interactive.cpp is not the expected v5.0.0 source (${part}); cannot apply the Windows input fix")
    endif()
    string(REPLACE "${old_${part}}" "${new_${part}}" text "${text}")
  endforeach()
  file(WRITE "${file}" "${text}")
  message(STATUS "Patched FTXUI Windows input (surrogate pairs)")
endfunction()
